from fpdf import FPDF
import os
import numpy as np
from PIL import Image
from disease_info import disease_details

REPORTS_DIR = "reports/"
EXPLAIN_DIR = "explainability/"

os.makedirs(REPORTS_DIR, exist_ok=True)

def generate_pdf_report(image_pil, prediction, confidence):
    pdf_path = os.path.join(REPORTS_DIR, "AI_Skin_Report.pdf")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 10, "AI Skin Cancer Detection Report", ln=True, align="C")
    pdf.ln(10)

    # Image
    img_path = os.path.join(REPORTS_DIR, "uploaded_temp.jpg")
    image_pil.save(img_path)
    pdf.image(img_path, x=35, w=140)
    pdf.ln(10)

    # Prediction
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Prediction: {prediction}", ln=True)

    # Confidence
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Confidence: {confidence:.2f}", ln=True)
    pdf.ln(5)

    # Disease Information
    info = disease_details[prediction]

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Severity:", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, info["severity"])
    pdf.ln(3)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Description:", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, info["description"])
    pdf.ln(3)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Advice:", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, info["advice"])
    pdf.ln(5)

    # Optional Grad-CAM Image
    grad_path = os.path.join(EXPLAIN_DIR, "gradcam_output.png")
    if os.path.exists(grad_path):
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Grad-CAM Heatmap:", ln=True)
        pdf.image(grad_path, x=35, w=140)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(0, 8, "Disclaimer: This report is generated by an AI model and is for "
                         "educational and research purposes only. It is not a medical diagnosis.")

    pdf.output(pdf_path)

    return pdf_path
